kind: pipeline
name: default

steps:
- name: update usage section in README.me
  image: python:3.11
  commands:
  - pip install poetry==1.7.1
  - poetry install --with dev
  - poetry run python drone/update_readme_cli_args.py
  - echo "[START]  PRINTING README"
  - cat README.md
  - echo "[FINISH] PRINTING README"

- name: git-push
  image: appleboy/drone-git-push
  settings:
    branch: dev
    remote: git@git.envs.net:myxi/glowl.git
    force: false
    commit: true
    author_name: "drone"
    commit_message: "drone: auto-update usage section"
    ssh_key:
      from_secret: SSH_KEY
